Repository Keerat666/Sapien, pull requests merged in 2025-10, with the labels that each got.

#31 docs: add contributor guidelines to README
  ui/README.md
Labels: good first issue, hacktoberfest-accepted

#23 feat: integrate Swagger for API documentation
  app.js
  docs/swagger-config.js
  package.json
  routes/health.js
Labels: hacktoberfest-accepted

#27 chore: update author meta tag and remove unused placeholder SVG
  ui/index.html
  ui/public/favicon.ico
  ui/public/placeholder.svg
Labels: hacktoberfest-accepted

#28 feat: add user model with validation and schema definitions
  models/users.js
Labels: hacktoberfest-accepted

#29 feat: implement MongoDB connection with error handling
  app.js
  middlewares/connection.js
Labels: hacktoberfest-accepted

#48 refactor: implemented MVC architecture
  app.js
  config/constants.js
  config/database.js
  controllers/commentsController.js
  controllers/healthController.js
  controllers/promptsController.js
  controllers/usersController.js
  docs/MVC_ARCHITECTURE.md
  middlewares/errorHandler.js
  middlewares/notFound.js
  middlewares/upload.js
  package.json
  routes/comments.js
  routes/health.js
  routes/promptRoutes.js
  routes/prompts.js
  routes/users.js
  services/commentsService.js
  services/promptsService.js
  services/usersService.js
  validators/commentValidators.js
  validators/promptValidators.js
  validators/userValidators.js
Labels: hacktoberfest-accepted

#59 feat: Add /prompts/recent API endpoint with pagination
  controllers/promptsController.js
  package.json
  routes/prompts.js
  scripts/seedPrompts.js
  services/promptsService.js
Labels: enhancement, hacktoberfest-accepted

#64 # BUG : Infinite Text box model in Profile page
  ui/src/components/EditProfileDialog.tsx
Labels: bug, hacktoberfest-accepted, ui, hacktoberfest, hacktoberfest2025-accepted, hacktoberfest2025

#67 Logo updated
  package-lock.json
  ui/package-lock.json
  ui/public/logo1.png
  ui/public/logo2.png
  ui/public/logo3.png
  ui/src/components/HeroSection.tsx
  ui/src/components/Navigation.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted, hacktoberfest2025

#65 Fixed BUG - Comments Overflow Issue #62
  ui/src/components/CommentSection.tsx
Labels: bug, hacktoberfest-accepted, ui, hacktoberfest, hacktoberfest2025-accepted, hacktoberfest2025

#69 Fixed textarea focus loss in reply form
  ui/src/components/CommentSection.tsx
Labels: bug, hacktoberfest-accepted, ui, hacktoberfest, hacktoberfest2025-accepted, hacktoberfest2025

#71 added home endpoint
  app.js
  controllers/homeController.js
  routes/home.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted, hacktoberfest2025

#73 Add scroll-to-top functionality
  ui/src/components/Footer.tsx
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted, hacktoberfest2025
